### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by MAGNAT2645** [pk-hack/CoilSnake#212]
1: Is there any proper way to move Status Text **Numbers** (like " 30/ 30" near **Hit Points:**)
Maybe there's ASM code somewhere?
I just want to shift the text and its numbers slightly to the left from stats (like Offense, Defense etc.)
![Image](https://user-images.githubusercontent.com/11666918/68993467-59a20e80-089a-11ea-9fb1-457ab11ae95f.png)

2: Lumine Hall Text displays weird. It shows translated part (like i wanted) but after my translation there's some original (english) words.
Why is this happening?
![WTF_Lumine](https://user-images.githubusercontent.com/11666918/68993299-468e3f00-0898-11ea-9e92-78d019021eaf.gif)
(prints something with "or are they?" at the end, as if not completely overrides the text)

This is "Other" category from text_misc:
```
Other:
  #  "Я ....  Мне пришлось преодолеть многое, чтобы сюда попасть...  Скоро, я буду...
  #  Скоро, я буду...  Что же случится с нами?  Ч...что происходит?
  # Мои мысли отображаются на стене...  или...?"
  Lumine Hall Text: "[B6] ....  [7E][9F][96] [A1][A2][9A][AA][9D][A0][A3][C3] [A1][A2][96][A0][95][A0][9D][96][A4][C3] [9E][9F][A0][94][A0][96], [A9][A4][A0][92][C2] [A3][C5][95][91] [A1][A0][A1][91][A3][A4][C3]...  [83][9C][A0][A2][A0], [C6] [92][A5][95][A5]...
    [83][9C][A0][A2][A0], [C6] [92][A5][95][A5]...  [89][A4][A0] [98][96] [A3][9D][A5][A9][9A][A4][A3][C6] [A3] [9F][91][9E][9A]?  [89]...[A9][A4][A0] [A1][A2][A0][9A][A3][A7][A0][95][9A][A4]?
    [7E][A0][9A] [9E][C2][A3][9D][9A] [A0][A4][A0][92][A2][91][98][91][C5][A4][A3][C6] [9F][91] [A3][A4][96][9F][96]...  [9A][9D][9A]...?"
  Player Name Prompt: "[81][A0][98][91][9D][A5][9B][A3][A4][91], [93][91][AA][96] [9A][9E][C6]." # Пожалуйста, ваше имя.
```

Also, does l_0xc937d9 (from data_51) have anything to do with this problem?

**Comment by RichardBukor** [comment]
At ROM address $EFA3B6 is the text data for the Status window, but it doesn't include the numbers, so you can change the text but it wont affect the numbers.

As for the numbers, you can try editing the following bytes. Keep in mind I haven't tested this in any capacity, so it's probably safe to create a backup or something.

All of these are only 1-byte changes. These are the same units used for the [18 05 XX YY] control code. Notice that "YY" comes before "XX" in this case.
```
LEVEL:
$C195AC - Level number Y position in Status window
$C195AF - Level number X position in Status window

HIT POINTS:
$C195D8 - Current HP number Y position in Status window
$C195DB - Current HP number X position in Status window

$C195F6 - HP divisor Y position in Status window ('/' character)
$C195F9 - HP divisor X position in Status window ('/' character)

$C19606 - Max HP number Y position in Status window
$C19609 - Max HP number X position in Status window

PSYCHIC POINTS:
$C19624 - Current PP number Y position in Status window
$C19627 - Current PP number X position in Status window

$C19642 - PP divisor Y position in Status window ('/' character)
$C19645 - PP divisor X position in Status window ('/' character)

$C19652 - Max PP number Y position in Status window
$C19655 - Max PP number X position in Status window

EXPERIENCE POINTS:
$C19780 - Current experience points number Y position in Status window
$C19783 - Current experience points number X position in Status window

EXP REMAINING FOR NEXT LEVEL:
$C197CA - Exp remaining number Y position in Status window
$C197CD - Exp remaining number X position in Status window
```

Also, please notice I've never used CoilSnake. I just reverse-engineer this game for fun, helping out the hacking community in the process of discovering new things in the game.

Someone who has CCScript/CoilSnake knowledge might be able to articulate my response into something you can use more easily.

**Comment by MAGNAT2645** [comment]
Also, what are their default values? I want to put these default values to CCScript file so i can start from initial number positions.

**Comment by RichardBukor** [comment]
Oh. Their defaults are the following:

(Numbers in hexadecimal)
```
$C195AC = 00
$C195AF = 26

$C195D8 = 03
$C195DB = 5E

$C195F6 = 03
$C195F9 = 72

$C19606 = 03
$C19609 = 79

$C19624 = 04
$C19627 = 5E

$C19642 = 04
$C19645 = 72

$C19652 = 04
$C19655 = 79

$C19780 = 05
$C19783 = 61

$C197CA = 06
$C197CD = 0A
```

**Comment by MAGNAT2645** [comment]
I also tried to use ASM functions like LDX_i, LDY_i, LDA_i and CMP_i but all of them just crash the game.

**Comment by MAGNAT2645** [comment]
Enough time has passed, and I have not yet solved the problems above.
Also, i have another question about event flags. Problem is that i can't control event flags using Debug Menu because it seems that toggle(**0**) doesn't work.

**Comment by PhoenixBound** [comment]
I'm not sure what's going on with Lumine Hall. I think it's a bug, but I'm surprised nothing like it has been included in the CoilSnake wiki. (Was the part at the beginning of the text where Ness's name was printing correctly? I couldn't get it to work in my testing, it would print in the middle of some words...)

Be sure to only use ASM in assembly routines. They can't be used in scripts, because the game is looking for text characters and script control codes, not assembly code.

As for event flags, I recommend using the ["main" debug menu](https://tcrf.net/EarthBound/Boot-Up_Debug_Menu#View_Map) to edit them. To access it, you first should enable the cheat code `7E436C01`. Then open the pause menu, press **and hold** B to close the menu, and press R. The "Flag" option in the window that opens will let you enable and disable flags.

**Comment by MAGNAT2645** [comment]
In Lumine Hall, English text appears here:
![изображение](https://user-images.githubusercontent.com/11666918/74926132-389c0d00-53f7-11ea-94a4-cbabc580f6ca.png)

About Status text, so i can't just use something like this?
```
ROM[0xC195D8] = LDX_i(0x0003) // Current HP number Y position
ROM[0xC195DB] = LDX_i(0x005E) // Current HP number X position
```

ROM Debug Menu is a little buggy (menu position is weird etc.) in my localization and often crashes the game. I used some patches from MaternalBound Redux for this Debug Menu.

**Comment by PhoenixBound** [comment]
Status text: I see. The addresses you're using there are in the middle of instructions rather than replacing the instructions entirely. One way to quickly fix this situation is to replace the `LDX_i(0xXX)` commands with `byte 0xXX`. (A different way involves looking at [the original ASM code you're editing](https://earthbound-rom-explorerr.herokuapp.com/address/$C1952F) and using the addresses and instruction names listed there, e.g. `ROM[0xC195DA] = LDA_i(0x005E)` for HP number X position.)

I need to research the other issues more before I can offer any help with them.

**Comment by MAGNAT2645** [comment]
So, issue with Status Text was solved, thanks.
![изображение](https://user-images.githubusercontent.com/11666918/75058897-b8140400-54fd-11ea-9d18-3261eef10960.png)

There's only one little problem (bug?), Jeff's max PP is a little out of place.
![изображение](https://user-images.githubusercontent.com/11666918/75058997-dbd74a00-54fd-11ea-9224-ffd46300d75f.png)
Could this happen because there's a different address for Jeff's max PP?

**Comment by MAGNAT2645** [comment]
Oh no, there's a problem with X position i think because this also happened to Ness.
![изображение](https://user-images.githubusercontent.com/11666918/75059196-45575880-54fe-11ea-8c85-4d3692d900b9.png)

**Comment by ShadowOne333** [comment]
Is it okay to close this issue?

**Comment by MAGNAT2645** [comment]
I still have a problem with Lumine Hall Text, so idk.

**Comment by ShadowOne333** [comment]
Have you modified the text at `l_0xc937d9` to match what you have in text_misc.yml?

**Comment by MAGNAT2645** [comment]
Yes, but does this label really matter?

**Comment by ShadowOne333** [comment]
I'm not sure to be honest.
One thing you could do, is to do a manual Hex search on the compiled ROM to whatever the Hex equivalents of the letters after the ending `или...?`, to see exactly where they are being written to, and then try to make a search on CoilSnake for anything close to that in any ccs file. (Or edit the Hex manually altogether)

**Comment by MAGNAT2645** [comment]
I think, better way to properly edit this text is to use CCScript (maybe use [00] at the end?)

**Comment by ShadowOne333** [comment]
That could do it, yeah.
It's worth the shot. Put the `[00]` after the question mark of `или...?` and see if that stops the reminding letters.

**Comment by MAGNAT2645** [comment]
Okay. First i will try to add [00] to the text_misc (but im not sure if this will work) and also add same [00] to data_51.l_0xc937d9.
Second i will need the pointer where this text begins (for CCScript).
I don't understand disassembling very well so i can search for this pointer (or check CoilSnake source).

**Comment by MAGNAT2645** [comment]
Uhhh, didn't help.
![изображение](https://user-images.githubusercontent.com/11666918/75362962-452ed280-58db-11ea-89fc-a581e7b0c180.png)
(it seems that first remaining letters now replaced with 00)

**Comment by ShadowOne333** [comment]
What about...
Try putting 9 blank spaces after the last question mark, see what that does in-game.

**Comment by MAGNAT2645** [comment]
This could work, i will try right now

**Comment by MAGNAT2645** [comment]
Yeah, it seems that problem fixed.
![изображение](https://user-images.githubusercontent.com/11666918/75363628-3137a080-58dc-11ea-9921-f118e9aaa8fa.png)

**Comment by MAGNAT2645** [comment]
So, yeah. I've just shortened the text a bit and remaining letters still there (now i need to fix this) but now we know how to workaround this.

I'll close this for now.

**Comment by ShadowOne333** [comment]
Great!
Nice to know it's working fine now :)
