### ISSUE TITLE
Need more space in fonts to add more characters 

### ISSUE THREAD

**Issue by KKha-11** [pk-hack/CoilSnake#219]
I'm planning to translate Earthbound into Vietnamnese and I need more space in font.png so i can fully translate the game, 32 more characters is not enough. Can I get like more than 120 characters?

**Comment by ShadowOne333** [comment]
You could replace the ones already available in the font files, alongside the extra 32 characters, but beyond that, sadly I don't think it's possible at the moment to have such an extensive amount of characters available.

**Comment by KKha-11** [comment]
So 32 more is max? Maybe I only need 64 or 50 characters more

**Comment by KKha-11** [comment]
> You could replace the ones already available in the font files, alongside the extra 32 characters, but beyond that, sadly I don't think it's possible at the moment to have such an extensive amount of characters available.

**Comment by KKha-11** [comment]
> You could replace the ones already available in the font files, alongside the extra 32 characters, but beyond that, sadly I don't think it's possible at the moment to have such an extensive amount of characters available.
So 32 more is max? Maybe I only need 64 or 50 characters more
Also if i delete the ';' or ':' in font.png and replace it with some other characters, wiil it effect anthing to the game?

**Comment by ShadowOne333** [comment]
32 additional ones besides from the ones already in the font, yes, that's the max.

And yes, you can do what  you mention (which is what I meant by "You could replace the ones already available in the font files").

You can get rid of other characters from the original game which you think wouldn't be used as much, just be sure that when you translate the game, you won't use them at all.
Don't forget to also edit the width files accordingly.

If in the extreme case that you still don't have the required character amount, you could also completely get rid of either lower case letters and handle everything in upper case, or get rid of upper case and handle it all lower case, etc. But that's in the most extreme cases.

Try replacing the most unused characters first, hopefully that should do it.
