### ISSUE TITLE
Can't regconize Earthbound Japan.ver's rom

### ISSUE THREAD

**Issue by KKha-11** [pk-hack/CoilSnake#223]
I have tried both PK Hack and Coilsnake to open EB Japan's rom, but those two don't regconize it

**Comment by ShadowOne333** [comment]
You mean "Mother 2" then, not really EarthBound.
Both PK Hack and CoilSnake don't have support for Mother 2 ROMs, only for the original USA release of the game.
There's no current hacking tool that supports Mother 2 that I know of.
