### ISSUE TITLE
Coilsnake does not show up?

### ISSUE THREAD

**Issue by PH1912** [pk-hack/CoilSnake#224]
I cannot see Coilsnake 4.0 despite the fact that my pc shows it open.
![image](https://user-images.githubusercontent.com/62227764/87710565-95390380-c7ae-11ea-9ab7-a7d8f6f4e6bd.png)
Anyone know how to fix this?

**Comment by PhoenixBound** [comment]
Hover over the icon in your taskbar. It'll show a preview of the window. Right-click on the preview and hit the button labeled "Maximize." It should appear on your screen. Then you can drag the CoilSnake window by the bar at the top to make it un-maximized again.

**Comment by PH1912** [comment]
Thanks!

**Comment by FallowWing** [comment]
This still happens of course, and confuses people. There's a good chance it's related to multiple/switched monitors and this PR: https://github.com/pk-hack/CoilSnake/pull/197
