### ISSUE TITLE
CoilSnake complains about free space problems for no apparent reason

### ISSUE THREAD

**Issue by PhoenixBound** [pk-hack/CoilSnake#225]
In the current CoilSnake project for Mother 2 Deluxe, CoilSnake sometimes claims that it runs out of free space when it tries to insert the map tilesets:

```
Traceback (most recent call last):
  File "coilsnake\ui\gui.py", line 302, in _do_compile_help
  File "coilsnake\ui\common.py", line 162, in compile_project
  File "coilsnake\modules\eb\TilesetModule.py", line 152, in write_to_rom
  File "coilsnake\model\eb\map_tilesets.py", line 137, in arrangements_to_block
  File "coilsnake\model\common\blocks.py", line 278, in allocate
coilsnake.exceptions.common.exceptions.NotEnoughUnallocatedSpaceError: NotEnoughUnallocatedSpaceError: Not enough free space left
```

Free space doesn't appear to be the actual problem, however. The output ROM before this message appears has nearly 6 banks' worth of free space. The message will go away when, for example, an edit to a battle background is undone or the disassembly for EB++ is removed. Somehow I don't think those solutions are solving an issue with free space.

At the very least, you'd expect some error before CoilSnake gets all the way to the tileset module.

**Comment by 24afortenbacker** [comment]
EarthBound has an anti-piracy measure that gets triggered if it detects any free space in the cartridge/ROM.

**Comment by Messianic** [comment]
It seems that this has nothing to do directly with EBPP. However if many graphical things are modified, such as adding unique battle sprites, unique sprite groups, and unique battle backgrounds, this error occurs. The common link is they are all graphical in nature, but editing them shouldn't change anything, even when battle sprite sizes are changed from 64x64 to 128x128.

Coilsnake should not be unable to compile this and even more so should be giving a CORRECT error message instead of one related to map tilesets.

**Comment by Messianic** [comment]
So where Coilsnake starts compiling into the expanded meg is controllable by the Settings > Configure CCScript option on Coilsnake itself. When Coilsnake says "Found range[(0xXXXXXX,0xXXXXXX)] used during compilation" It is both stating where ALL compilation into the expanded meg begins, but the specified range is only for CCScript, it will compile beyond that to an undisclosed point in the ROM.


In my case it was actually compiling right to the end of the expanded space, making me think it stopped far before that. After tidying some things up and manually setting the compilation point earlier, I freed up enough space to stop getting this error.

**Comment by ShadowOne333** [comment]
The comment above explains how and why the error occurred.
Thanks for the comment, Messianic. I will now properly close this issue.
