### ISSUE TITLE
EB Project Editor Loading Problem

### ISSUE THREAD

**Issue by MAGNAT2645** [pk-hack/CoilSnake#226]
EB Project Editor prints `Status: Loading Tile ...` and nothing happens.
![изображение](https://user-images.githubusercontent.com/11666918/89278853-13772000-d660-11ea-873f-462eda3aaa08.png)
So i cant use any tools.
Does Project Editor log something?

**EDIT**:
**OS**: Windows 7 x64
**JRE**: AdoptOpenJDK JRE 14.0.2.12 with OpenJ9

**Comment by 24afortenbacker** [comment]
If you have decompiled an Earthbound ROM and open the editor through Coilsnake, it should load just fine.

**Comment by MAGNAT2645** [comment]
I'm opening existing project (EB Project Editor worked fine before with my project).

**Comment by 24afortenbacker** [comment]
Then you need to make sure your tile sets have the correct endings. Try downloading Notepad++ because other editors can screw with the order of the data.

**Comment by MAGNAT2645** [comment]
The problem is that tilesets work fine in the game. I just cant load Tile/Map Editor because Project Editor does nothing but prints `Loading Tile ...`

**Comment by 24afortenbacker** [comment]
You might have to reinstall the project editor, I'm not an expert.

**Comment by MAGNAT2645** [comment]
How can i reinstall Project Editor if it is like built into CoilSnake?

**Comment by 24afortenbacker** [comment]
You gotta reinstall CoilSnake but I probably have no idea what I'm talking about.

**Comment by 24afortenbacker** [comment]
I can't even work a hex editor properly.

**Comment by MAGNAT2645** [comment]
CoilSnake itself is one `.exe` file. I don't think that reinstalling CoilSnake would help.

**Comment by 24afortenbacker** [comment]
yeah i just don't know what i'm doing
i just started rom hacking like a month ago and i need a lot of help

**Comment by PhoenixBound** [comment]
This sort of thing is related to the line endings (CRLF or LF) in some of the files EBProjEditor uses.

Open "C:\Users\<your name>\.ebprojeditor\EbhackPrefs.yml" in a text editor like Notepad++.

On the status bar at the bottom, you should see some text labeled "Unix (LF)" or "Windows (CRLF)." If it says Windows, then right-click it and change it to Unix.
![image](https://user-images.githubusercontent.com/13182187/89446346-0a4a8980-d71a-11ea-8c6d-cf8222e180c1.png)

If that doesn't work, then you can manually inspect the line endings in a text file by going to "View" --> "Show Symbol" --> "Show End of Line." If you see a line ending that doesn't match the others with this option on, you can just delete it and type "Enter" to make a new one.
![image](https://user-images.githubusercontent.com/13182187/89446728-8513a480-d71a-11ea-924c-6838bd488760.png)

**Comment by MAGNAT2645** [comment]
`EbhackPrefs` has `LF` endings.
Which files do i need to check?

**Comment by PhoenixBound** [comment]
The FTS files in your project's "Tilesets" folder may be worth checking first

**Comment by MAGNAT2645** [comment]
> 
> 
> The FTS files in your project's "Tilesets" folder may be worth checking first

FTS files has Windows endings. Should i change them to Unix?

**Comment by MAGNAT2645** [comment]
Wait, something is not right...
![изображение](https://user-images.githubusercontent.com/11666918/89455759-3a2a7900-d77c-11ea-9d4b-5533d6786d35.png)

**Comment by ShadowOne333** [comment]
So it's working properly now?
I just saw this, if you need me to reopen the issue, or if you fixed it already, please let me know.

**Comment by MAGNAT2645** [comment]
Yeah, it's fine.
