### ISSUE TITLE
 Unknown pointer label[robot.hello_world]

### ISSUE THREAD

**Issue by TheNooseMan87** [pk-hack/CoilSnake#229]
So i got the message "TableEntryInvalidYmlRepresentationError: Unknown pointer label[robot.hello_world]" while compiling my rom. so, i looked at the trouble shooting page, and sure enough, it was shown there. i fixed the file and named it to robot.ccs. it still does not work.

**Comment by LittlestCube** [comment]
How are you defining and calling `robot.hello_world`? What troubleshooting page? I looked and there doesn't seem to be a real troubleshooting page in the wiki (it's red and seems to be uncreated), but I might be able to help if you give me a bit more info.

**Comment by ShadowOne333** [comment]
Did you add a proper label?
You should have something like this inside your `robot.ccs` file:

```hello_world:
    "@Here goes your code or text"```

**Comment by TheNooseMan87** [comment]
Sorry, it was late at night and i was getting a bit stressed, and i was not thinking much, I'll retell the story. So, i was following the guide and everything was going ok. i was following everything, copy and pasting text where it belongs, and putting the little robot guy on the map, and putting in the right code for him. but when i tried to compile it, it gave me theses exact error messages:
"TableError: Error while parsing in "Text Pointer 1" in entry #744 in table "NPC_CONFIG_TABLE":
TableSchemaError: Error while parsing "Text Pointer 1":
TableEntryInvalidYmlRepresentationError: Unknown pointer label[robot.hello world!]"
i looked down to the troubleshooting section of the guide i was reading, and it showed that same error message i was getting, with some solutions. so made sure everything is correct. but it still gives me the same message. I have checked everything more times an i can count. and i still don't know what is wrong.

**Comment by ShadowOne333** [comment]
Have you tried putting `robot.hello_world` in between quotation marks?
Like this:

`"robot.hello_world"`

**Comment by TheNooseMan87** [comment]
In what? if your talking about the npc configuration table then it doesn't work, but thanks anyways.

**Comment by ShadowOne333** [comment]
Where did you put the `robot.hello_world` command in your project?
What file precisely? If you can, please take a screenshot of the exact file and line where you put that so we can have a better understanding of what might be wrong.

**Comment by TheNooseMan87** [comment]
don't know how to screenshot but its in the 744th slot of the Npc_config_table
heres what it looks like

744:
  Direction: down
  Event Flag: 0x0
  Movement: 605
  Show Sprite: always
  Sprite: 5
  Text Pointer 1: robot.hello_world
  Text Pointer 2: $0
  Type: person

**Comment by ShadowOne333** [comment]
And do you actually have a `robot.ccs` file inside the `ccscript` folder?
And inside that file, you need to have:
 ```
 hello_world:
     "@Here goes your code or text"
 ```

**Comment by TheNooseMan87** [comment]
yes, it looks like this:

hello_world:
    "@Hello World!" end

**Comment by ShadowOne333** [comment]
There's something odd.
Check that the NPC text pointer actually has `robot.hello world` and NOT `robot.hello world!` with an exclamation mark at the end.
The error you show apparently writes it with an exclamation mark.
Make sure the name of the label inside the NPC yml file and inside the robot.ccs is the same.
The text in between quotation marks doesn't matter, just the label name.

**Comment by TheNooseMan87** [comment]
sorry, could you please elaborate on what you mean by "Make sure the name of the label inside the NPC yml file and inside the robot.ccs is the same."

**Comment by ShadowOne333** [comment]
It means that the name that you put here:
`Text Pointer 1: robot.hello_world`

Should match 1:1 the name of the label inside the robot.ccs file:
```
hello_world:
    "@Here goes your code or text"
```

You need to be absolutely sure there's no extra character in there, as the error seems to throw an exclamation mark in the .yml file

**Comment by TheNooseMan87** [comment]
oh, just tried it, didn't work though

**Comment by ShadowOne333** [comment]
What you write the exact error output again, please?

**Comment by TheNooseMan87** [comment]
TableError: Error while parsing in "Text Pointer 1" in entry #744 in table "NPC_CONFIG_TABLE":
TableSchemaError: Error while parsing "Text Pointer 1":
TableEntryInvalidYmlRepresentationError: Unknown pointer label[robot.hello_world]

**Comment by ShadowOne333** [comment]
It should work. Are you absolutely sure that:
1) The `hello_world` is written exactly the same in the yml and ccs files
2) The `robot.ccs` file is inside the `ccscript` folder

**Comment by TheNooseMan87** [comment]
in my yml file, its wrote as robot.hello_world and its only hello_world in the ccsript, but otherwise, yes.

**Comment by ShadowOne333** [comment]
Okay then let's try something different.
Write this inside data_00.ccs
```
hello_world:
    "@Hello world!" end
```
Then at the Text pointer, change it to this:
`Text Pointer 1: data_00.hello_world`

If that doesn't work, I don't know what would

**Comment by TheNooseMan87** [comment]
at the top of the page?

**Comment by ShadowOne333** [comment]
Before the other labels begin. Or anywhere after the `command e(label)` line should work too

**Comment by TheNooseMan87** [comment]
OMG IT WORKED!!! thank you so much! it makes me so happy that you would spend 30 minutes of your day just to help some random stranger. Really, i mean it, thanks a lot.

**Comment by ShadowOne333** [comment]
You're welcome :)
I'm glad it finally worked, I'll be closing the issue now.

That means that perhaps the issue was indeed in the file name, or maybe there was a typo somewhere.
You can continue working that way. By adding labels into already existing data_XX files, but it's suggested to create new .CCS files so that you don't make it messy.
But if this new method works better for you without bringing the issue again, then it's fine.
