### ISSUE TITLE
Dropbox links not work

### ISSUE THREAD

**Issue by Daskoul** [pk-hack/CoilSnake#233]
asm65816.ccs: https://dl.dropboxusercontent.com/u/8482/MiscText/asm65816.ccs
Bash: https://dl.dropboxusercontent.com/u/8482/MiscText/bash.ccs
Row Front: https://dl.dropboxusercontent.com/u/8482/MiscText/Row_Front.ccs

**Comment by PhoenixBound** [comment]
This is a bug tracker for CoilSnake, not a support forum for EarthBound hacking. These links don't seem to show up anywhere in CoilSnake's code.

The first one, asm65816, is available in the CCScript Library on the wiki. I have no idea what the other two are supposed to be.

**Comment by Daskoul** [comment]
the likns in the https://github.com/pk-hack/CoilSnake/wiki/Tutorial%3A-Translating-Misc-Text and at the bottom of the site it says submit an issue in the need more help section so I wrote it here sorry for wrong use

**Comment by Daskoul** [comment]
> This is a bug tracker for CoilSnake, not a support forum for EarthBound hacking. These links don't seem to show up anywhere in CoilSnake's code.
> 
> The first one, asm65816, is available in the CCScript Library on the wiki. I have no idea what the other two are supposed to be.

the links in the https://github.com/pk-hack/CoilSnake/wiki/Tutorial%3A-Translating-Misc-Text and at the bottom of the site it says submit an issue in the need more help section so I wrote it here sorry for wrong use

**Comment by PhoenixBound** [comment]
Oh, it is in the wiki then. Sorry. Asking around about it now.

**Comment by ShadowOne333** [comment]
I believe you can get the asm65816.ccs from the CCScript Library in the Wiki:
https://github.com/pk-hack/CoilSnake/wiki/CCScript-Library

As for the bash.ccs and Row_Front.ccs, I believe this is what those files had:

Row_Front.ccs:
```
import asm65816
    ROM[0xC1219A] = ASMLoadAddress06 (row_front)

    row_front:
    “fila[bf]da[bf]frente[ 00 ]”
```

bash.ccs:
```
 import asm65816
    ROM[0xC235F5] = ASMLoadAddress0E (bash)
    ROM[0xC23660] = ASMLoadAddress0A (bash)
    ROM[0xC2370C] = ASMLoadAddress06 (bash)

    bash:
    “bash[bf]here[ 00 ]”
```

Hope this helps!

**Comment by Daskoul** [comment]
Thank you very much!

**Comment by ShadowOne333** [comment]
TragicManner was kind enough to resend us the official files he used.
You can find them attached to this post.
I will add them to the official tutorial in a while.

[Tutorial Files.zip](https://github.com/pk-hack/CoilSnake/files/5789185/Tutorial.Files.zip)

I think with that, we can safely close up this issue.
If you feel something is still pending, let me know and I'll reopen it.
