### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by Nyoki20** [pk-hack/CoilSnake#234]
Hi there! I can´t do the decompile because a message shows up:
errno 13 permission denied : ´C: /User/X/Pictures\\ccsript/summary.text 

What can i do? Thank you for reading.

**Comment by ShadowOne333** [comment]
What operating system are you working on?
According to the log, the issue seems to be related to permissions in your system.
Make sure you have the proper permissions to edit files in that directory.

**Comment by Nyoki20** [comment]
I have Windows 10. I am begginer in this, so there are things that i don´t understand pretty well
Thank you for answering ٩(｡•́‿•̀｡)۶ (〃＾▽＾〃) (´｡• ᵕ •｡`)
--



--



--

**Comment by LittlestCube** [comment]
Just in case you haven't solved this yet:

Someone used to say that a good way to make sure that there aren't any permission issues on Windows is to create a new CoilSnake folder on your Desktop, and try working from there.

**Comment by ShadowOne333** [comment]
Please, let us know if the issue was fixed by simply giving the proper permissions to the user.
(I'll assume the issue has been fixed and will be properly closed if there hasn't been a response by the end of the month)
