### ISSUE TITLE
Last credits photo is messed up

### ISSUE THREAD

**Issue by dnm4** [pk-hack/CoilSnake#235]
After compiling a project, even a freshly decompiled and unmodified one, the final credits photo appears like this when I use the recommended save states.
![EB000](https://user-images.githubusercontent.com/77656484/104991554-3d3cbd00-59dc-11eb-9bbf-a6521f14d300.png)

Is this just an issue with using savestates from the unmodified version of the game? It would suck to play through the entire game and see this.
The photo appears correctly when I use the same save state with other people's patches.

**Comment by ShadowOne333** [comment]
Use of save states is never encouraged when going between hacks.
Certain hacks move stuff around in the ROM, and loading a save state can trigger unwanted results, like glitched graphics or weird behaviours in the game.

Please, try loading the game normally, from the File Select menu, and continue to the credits as you normally would.
Let us know if the photo works properly after loading the game and its save from the normal File Select menu.

**Comment by dnm4** [comment]
It seems to be working fine when I play through from the File Select. I just found it strange that this was the only error I encountered while testing with save states, and wasn't sure if that was the reason. Thanks for the help.

**Comment by ShadowOne333** [comment]
Ah I see.
Yeah then it was indeed caused by save states.
CoilSnake is known for relocating a lot of the game's assets as it sees fit within the ROM, so some assets might have shifted around between the ROM you made the save state with, and the hack you tried it with.

Glad it worked fine in the end!
