### ISSUE TITLE
Cant decompile scripts

### ISSUE THREAD

**Issue by Pykom** [pk-hack/CoilSnake#237]
I'm using a normal earthbound rom and I'm on coilsnake 4.0 on windows 10. Whenever I try to decompile scripts the green bar is just moving and never stops. I'm not getting any error messages but nothing happenes except the bar moving. I've seen other people talk about this but the issue doesn't seem to get resolved. Any fixes

**Comment by Rickisthe1** [comment]
Did you select your project folder or the ccscript folder inside it?

If you selected the ccscript folder inside it, that will happen. You have to have only your project folder selected.

**Comment by JimSlimTripleChin** [comment]
> Did you select your project folder or the ccscript folder inside it?
> 
> If you selected the ccscript folder inside it, that will happen. You have to have only your project folder selected.

I selected the project folder but its empty. Do I have to decompile before I decompile the scripts?
