### ISSUE TITLE
Help: How to remove opening cutscene?

### ISSUE THREAD

**Issue by kwagogames** [pk-hack/CoilSnake#247]
So I've recently tried out Coilsnake 4.1 and it's packed with features, and I'm excited to try it out!

However, I have come across an issue. I want to remove the opening cutscene (since my hack won't really need it), but I'm not sure how to do it.

I've tried looking through the main ccscript files, but to no avail.

 Is there a way to remove it?

(not sure if I should ask for help here but I will)

**Comment by ShadowOne333** [comment]
I think there's an option or something of the likes that helps with that, should be as simple as toggling it to "Enabled" in a certain YML file.
If I recall correctly, it should be the option called `Show Sprites Without Flyover` inside _patches.yml_.
Change that option to "Enabled", like follows:
`Show Sprites Without Flyover: enabled`

That should get rid of the starting cutscene, or as it's known in EarthBound coding, the "flyover" sequence.
Hope that helped! Please, let us know if this solved it so we can close the issue properly.
I'll wait a couple of days for it, if not then I'll close it by then.

**Comment by kwagogames** [comment]
Got it, thanks! It worked :)
