### ISSUE TITLE
"Failed to execute script gui" error shows up on start

### ISSUE THREAD

**Issue by LaxerOfficial** [pk-hack/CoilSnake#256]
hello, I'm monorono and I was planning into making a EB mod then this showed up
![Captura de tela 2022-04-25 152253](https://user-images.githubusercontent.com/31388544/165150742-4e9cb67c-688e-483e-9084-7e1880d57857.png)

what should I do?

Intel(R) Pentium(R) Dual CPU E2180 @ 2.00GHz 2.00 GHz
4,00 GB RAM
Windows 10 Pro version 21H2, 64 bits

**Comment by ShadowOne333** [comment]
Please refer to Issue #251 .
Try deleting your .coilsnake.yml file inside the folder "C:/Users/YourUserName".
That should fix it.
