### ISSUE TITLE
error

### ISSUE THREAD

**Issue by EnderBoi201** [pk-hack/CoilSnake#264]
CoilSnakeError: Image does not use an indexed palette: C:/Users/user/Downloads/earthboun\WindowGraphics/Windows1_1.png

**Comment by ShadowOne333** [comment]
You have to edit sprites and everything graphics related with GraphicsGale.
That error appears when you edit an image in a software that doesn't have Indexed Palettes enabled, use GraphicsGale to make your sprite edits instead.

**Comment by EnderBoi201** [comment]
thanks
