### ISSUE TITLE
Enemy compilation problem

### ISSUE THREAD

**Issue by Giegue-II** [pk-hack/CoilSnake#296]
I'm trying to compile an earthbound project but when coilsnake gets to compiling the enemies, it sys'(32, 34) is not in list' and I dont know what it means. Can anyone help me?

**Comment by PhoenixBound** [comment]
This error message has to do with sprite sizes. Battle sprites [can only have certain sizes](https://github.com/pk-hack/CoilSnake/wiki/Battle-Sprites), and 32 pixels wide by 34 pixels tall (the `(32, 34)` in the error message) isn't one of them. See the linked wiki page for what sizes can be used.

**Comment by Giegue-II** [comment]
Alright. Thank you very much!
