### ISSUE TITLE
PALETTTE ERRORS.

### ISSUE THREAD

**Issue by wolosolo** [pk-hack/CoilSnake#301]
so, i fixed sprite 001 but now sprite 461 has the same problem. i made this issue post because i didn't want to disturb the previous guy
since i accidentally closed and reopened the issue, and it looks REALLY bad on my part, so yeah, sorry for that, also here's the sprite

![461](https://github.com/user-attachments/assets/65b0fae5-ff14-49a4-bfa1-9f819b205536)

**Comment by Rickisthe1** [comment]
Have you tried using this super convenient tool that's been around this entire time? Might wanna use it. https://www.compnode.net/coilsnake/spritegroup-palettes.html
Instructions tell you what to do there. Hope this helps.

**Comment by wolosolo** [comment]
ok, thanks but this beast just appeared, what do i do now?

Compiling Compressed Graphics...
- Reading TownMaps/Onett
User input error: Could not fit all colors in 8x8 square at (80,16) into a single 16-color subpalette
Colors: [#000000, #f8f840, #9898f8]
Palette: [[#584890, #f0f0d0, #d0e0a8, #e09058, #987050, #f8f878, #7070f0, #f03888, #58f880, #00b058, #287850, #f8f8c8, #d0d0a8, #b8b880, #f8c020, #707070], [#f8f8f8, #d82890, #58b8c0, #f8f840, #f8f8f8, #a860b8, #a0a088, #f0e878, #50a078, #c8b8f0, #b8d8f8, #9898f8, #f8f800, #f8f800, #f8f800, #f8f800]]

**Comment by Rickisthe1** [comment]
There are too many colors in the 8x8 square at 80x, 16y. Reading the error message helps a ton. At those coordinates, remove some colors in the 8x8 square. I'd recommend not touching town maps until you actually know what you're doing. We have a huge wiki article full of all the information you could ever need about eb hacking.
