### ISSUE TITLE
Map YML's turning into nulls

### ISSUE THREAD

**Issue by RANDOMNE55** [pk-hack/CoilSnake#306]
Whenever I load my project into EBME or the map editor, all the map YML files get turned into nulls, meaning I have to restart. This has happened at least five times and it happens for no apparent reason.
\

**Comment by PhoenixBound** [comment]
As mentioned on the Discord server, this is probably an issue with EB Project Editor not understanding certain YAML features that EBME uses by default. Testing of a new version of the project editor with a new version of SnakeYAML is required. I've moved this issue to the EB Project Editor repository: https://github.com/pk-hack/EbProjectEditor/issues/21
