### ISSUE TITLE
GUI crashes in Windows

### ISSUE THREAD

**Issue by mrtenda** [pk-hack/CoilSnake#94]
The GUI crashes when the user is performing an operation (compiling, upgrading, etc).

My hypothesis is that the progress bar code may not be thread safe: http://effbot.org/zone/tkinter-threads.htm

Crash reports:

```
Compiling crash:
Faulting application name: CoilSnake.exe, version: 2.0.0.0, time stamp: 0×49180193
Faulting module name: tcl85.dll, version: 8.5.2.2, time stamp: 0×4c790429
Exception code: 0xc0000005
Fault offset: 0×0004b81a
Faulting process id: 0×327c
Faulting application start time: 0×01cf67131da3e181
Faulting application path: C:\Users\RYDEL_~1\AppData\Local\Temp\nsx62BA.tmp\CoilSnake.exe
Faulting module path: C:\Users\RYDEL_~1\AppData\Local\Temp\nsx62BA.tmp\tcl85.dll
Report Id: c2e5615a-d306-11e3-824f-60a44ce6d0ab
Faulting package full name: 
Faulting package-relative application ID:

Upgrade crash:
Faulting application name: CoilSnake.exe, version: 2.0.0.0, time stamp: 0×49180193
Faulting module name: tcl85.dll, version: 8.5.2.2, time stamp: 0×4c790429
Exception code: 0xc0000005
Fault offset: 0×00075d23
Faulting process id: 0×654
Faulting application start time: 0×01cf67120a9dc2ad
Faulting application path: C:\Users\RYDEL_~1\AppData\Local\Temp\nsd58BA.tmp\CoilSnake.exe
Faulting module path: C:\Users\RYDEL_~1\AppData\Local\Temp\nsd58BA.tmp\tcl85.dll
Report Id: 6ecdadab-d305-11e3-824f-60a44ce6d0ab
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by aaseagrass** [comment]
Hello Everyone! Hope there is someone here who is knowledgeable in creating GUI in Python using Qt creator and Qt designer. Right now, I'm having difficulty in doing the GUI in our senior's project. I'm working with PyQt4 library for our GUI however, yesterday our uimain for our GUI suddenly didn't pop up. Instead, this kind of syntax appears everytime I run my GUI .py code "Process finished with exit code -1073741819 (0xC0000005)" and the ui didn't show up. Anyone here who knows who to solve that kind error? Thank you very much! This will be a another great help for us.

**Comment by LittlestCube** [comment]
Does this have anything to do with the CoilSnake program?

**Comment by aaseagrass** [comment]
Sorry Sir but it seems it doesn't have any connection with the CoilSnake program, I'm just trying to ask this concern, thinking that someone here has an idea. Sorry for the inconvenience.
